name: Lighthouse CI

on:
  push:
    branches:
      - master

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Build
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Wait for deployment
        run: sleep 30

      - name: Run Lighthouse CI
        run: npx @lhci/cli autorun --collect.url=https://arnavk09.github.io/todoonglist/

      - name: Generate QR code for deployed site
        run: npx qrcode-terminal https://arnavk09.github.io/todoonglist/
